services:
  market-predictor:
    build: .
    container_name: market-predictor
    restart: always

    env_file:
      - .env

    environment:
      - PORT=${PORT}

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.market-predictor.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.market-predictor.entrypoints=websecure"
      - "traefik.http.routers.market-predictor.tls.certresolver=le"

      - "traefik.http.services.market-predictor.loadbalancer.server.port=${PORT}"

      - "traefik.http.middlewares.market-predictor-hsts.headers.stsSeconds=31536000"
      - "traefik.http.middlewares.market-predictor-hsts.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.market-predictor-hsts.headers.stsPreload=true"

      - "traefik.http.routers.market-predictor.middlewares=market-predictor-hsts@docker"

    networks:
      - web

    expose:
      - "${PORT}"

networks:
  web:
    external: true